### ISSUE TITLE
enabling a realm clears the value of eventsExpiration 

### ISSUE THREAD

**Issue by ghost** [adorsys/keycloak-config-cli#1018]
### Current Behavior

1. The user event expiration period (Realm Settings > Events > User event settings > Expiration , `eventsExpiration`) is removed when a realm is enabled using an isolated configuration file.

### Expected Behavior

When importing the config as shown below, I expect the value of `eventsExpiration` to stay unaffected

### Steps To Reproduce

1. Import the following configuration yaml file

```yaml
realm: dummy
eventsEnabled: true
eventsExpiration: 123
enabled: true
```
Result: The realm is created, enabled and the expiration period is set.

2. Now split the configuration in two separate files:
```yaml
# --- file 1 ---
realm: dummy
eventsEnabled: true
eventsExpiration: 123
```
and
```yaml
# --- file 2 ---
realm: dummy
enabled: true
```
and import both files at the same time.
Result: the value of `eventsExpiration` is empty.

### Environment

- Keycloak Version: 24.0.2
- keycloak-config-cli Version: 5.12.0
- Java Version: 17.0.11
