### ISSUE TITLE
Unrecognized field "required" in org.keycloak.representations.idm.ConfigPropertyRepresentation

### ISSUE THREAD

**Issue by thomasdarimont** [adorsys/keycloak-config-cli#1067]
### Current Behavior

The latest version of keycloak-config-cli 6.0.2-22.0.4 is not compatible with Keycloak 24.0.5.

```
keycloak-config-1  | 2024-06-20T23:20:36.901Z DEBUG 1 --- [           main] d.a.k.config.provider.KeycloakProvider   : Attempt failure #29: jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "required" (class org.keycloak.representations.idm.ConfigPropertyRepresentation), not marked as ignorable (8 known properties: "defaultValue", "readOnly", "label", "type", "name", "helpText", "secret", "options"])
keycloak-config-1  |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 28778] (through reference chain: org.keycloak.representations.info.ServerInfoRepresentation["protocolMapperTypes"]->java.util.LinkedHashMap["saml"]->java.util.ArrayList[0]->org.keycloak.representations.idm.ProtocolMapperTypeRepresentation["properties"]->java.util.ArrayList[0]->org.keycloak.representations.idm.ConfigPropertyRepresentation["required"])
```

### Expected Behavior

It should be possible to use the latest keycloak-config-cli version with Keycloak 24.x

### Steps To Reproduce

Docker-Compose file:

```yml
services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    environment:

      # Keycloak Admin User
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Feature config, see: https://www.keycloak.org/server/features
      KC_FEATURES: preview

      # Disable specific features
      #      KC_FEATURES_DISABLED: "device-flow"

      # Logging, see: https://www.keycloak.org/server/logging
      KC_LOG_LEVEL: INFO

      # External frontend hostname, see: https://www.keycloak.org/server/hostname
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: "8080"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: "/auth"

      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"

      # Log Keycloak success events to the console
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_SUCCESS_LEVEL: "info"
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_ERROR_LEVEL: "warn"

      # Additional JVM options
      JAVA_OPTS_APPEND: "--show-version"

      # Enable Remote Debugging
      DEBUG: "true"
      DEBUG_PORT: "*:18787"

    ports:
      - 8080:8080   # HTTP
      - 8443:8443   # HTTPS
      - 18787:18787 # Java Remote Debug

    command:
      - "--verbose"
      - "start-dev"

  keycloak-config:
    image: quay.io/adorsys/keycloak-config-cli:6.0.2-22.0.4
    environment:
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "180s"
      # see: https://github.com/adorsys/keycloak-config-cli/blob/v5.0.0/CHANGELOG.md
      IMPORT_FILES_LOCATIONS: "/config/*" # IMPORT_PATH: "/config"
      IMPORT_CACHE_ENABLED: "true" # IMPORT_FORCE: "false"
      IMPORT_VAR_SUBSTITUTION_ENABLED: "true" # IMPORT_VARSUBSTITUTION: "true"
      IMPORT_VALIDATE: "true"

      # See https://github.com/adorsys/keycloak-config-cli#log-level
      #LOGGING_LEVEL_KEYCLOAK_CONFIG_CLI: "DEBUG"
      # Note: the above does not work but _KCC does
      LOGGING_LEVEL_KCC: "DEBUG"

      # Veeeeery verbose HTTP log!
      #LOGGING_LEVEL_HTTP: "DEBUG"

      #LOGGING_LEVEL_ROOT: "DEBUG"
      LOGGING_LEVEL_ROOT: "INFO"

      KEYCLOAK_URL: "http://keycloak:8080/auth"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    volumes:
      - ./realms:/config:z
```

realms/up-demo.yaml
```yml
realm: up-demo
enabled: true
displayName: "UP Demo"

```

### Environment

- Keycloak Version: 24.0.5
- keycloak-config-cli Version: 6.0.2-22.0.4
- Java Version: openjdk version "17.0.11" 2024-04-16
