### ISSUE TITLE
Add mention of basic scope handling to migration guide

### ISSUE THREAD

**Issue by thomasdarimont** [adorsys/keycloak-config-cli#1073]
### Problem Statement

With the [introduction of the dedicated "basic" scope in Keycloak](https://www.keycloak.org/docs/latest/release_notes/index.html#lightweight-access-token-to-be-even-more-lightweight), existing realm configurations with custom clients might now produce access tokens that don't contain the `sub` claim anymore. This is because the new `basic` scope that emits those claims might be removed by an explicit `defaultClientScopes` configuration.

[The Keycloak 25 migration documentation documents](https://www.keycloak.org/docs/latest/upgrading/index.html#new-default-client-scope-basic) that the `basic` scope is automatically added to existing clients during realm migration, however some client configurations with a `defaultClientScopes` configuration might lack the `basic` scope configuration. In that case keycloak-config-cli will remove the `basic` scope again.

### Proposed Solution

Add a short note to the migration guide about the need to add the `basic` scope explicitly when a client configuration uses `defaultClientScopes`.

A workaround is to configure the `basic` scope explicitly via `defaultClientScopes`
```
    defaultClientScopes:
      - "basic"
```

### Environment

- Keycloak Version: 25.0.1
- keycloak-config-cli Version: 6.0.3-SNAPSHOT (cf28b9df)
- Java Version: 21

### Additional information

I think this is actually a regression in Keycloak, but some folks might blame keycloak-config-cli here.

Example of a previously working client definition, which will produce access tokens with the `sub` claim:
```yaml
  - clientId: app-greetme
    protocol: openid-connect
    name: Acme Greet Me
    description: "App Greet Me Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    # Show client in account-console
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: false
    #    attributes: { }
    fullScopeAllowed: false
    rootUrl: "$(env:APPS_FRONTEND_URL_GREETME:https://localhost:9443/apps/greet-me)"
    baseUrl: "/?realm=acme-internal&scope=openid"
    adminUrl: ""
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
    optionalClientScopes:
      - "phone"
      - "name"
      - "acme.api"
      - "address"
    attributes:
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"
```

Working client configuration:
```yaml
  - clientId: app-greetme
    protocol: openid-connect
    name: Acme Greet Me
    description: "App Greet Me Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    # Show client in account-console
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: false
    #    attributes: { }
    fullScopeAllowed: false
    rootUrl: "$(env:APPS_FRONTEND_URL_GREETME:https://localhost:9443/apps/greet-me)"
    baseUrl: "/?realm=acme-internal&scope=openid"
    adminUrl: ""
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "default"
      - "email"
    optionalClientScopes:
      - "phone"
      - "name"
      - "acme.api"
      - "address"
    attributes:
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"
```
