### ISSUE TITLE
SecurityContext settings in job template is wrong

### ISSUE THREAD

**Issue by andreasgeisslerdt** [adorsys/keycloak-config-cli#1087]
### Current Behavior

When I want to use the options: 
```
securityContext:
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
    - CAP_NET_RAW
```
the entries will not be set correctly in the resulting manifest

### Expected Behavior

Settings should be set to the manifest in the right way

### Steps To Reproduce

```markdown
1. set the values in values.yaml
2. compile chart
3. check schart
```

### Environment

- Keycloak Version: [e.g. 24.0.1]
- keycloak-config-cli Version: [e.g. 5.11.1]
- Java Version: [e.g. 21]

### Anything else?

Fix proposed in:
https://github.com/adorsys/keycloak-config-cli/compare/main...andreasgeisslerdt:keycloak-config-cli:patch-1
