### ISSUE TITLE
Question: Update BuiltIn Authentication Flows/SubFlows

### ISSUE THREAD

**Issue by magrossm** [adorsys/keycloak-config-cli#1251]
Hello,

thank you for your work and the keycloak-cli.

Following scenario:

I am using the keycloak-cli for configuration. Now I added a step (User count delimiter with user sessions) to builtin authentication flows, which are associated with a specific realm.

Now I want to add the correspondin step by the cli. 

Now assuming I have the relevant IDs and attributes of each flow/subflow, 

do I have to map the entire builtin flow into yaml/json format or can I update the flow by assigning the substep to the top level auth flow id with lets say a very high priority and the delta will be added. 

The flows are really extensive and I dont know how the mapping is done. Somewhere I read there is an export and matching of the realm auth flows, but not sure. I just dont want to map the entire builtin flow if I can just add the substep as a delta config.

Thank you for any information.

e.g. 

```
realm: myRealm
authenticationFlows:
- alias: builtin flow
        providerId: basic-flow
        topLevel: true
        builtIn: true
        authenticationExecutions:
          - authenticatorFlow: true
            requirement: REQUIRED
            priority: 999                                (must be hight to be added at the end)
            autheticatorFlow: true
            flowAlias: my-first-broker-login User creation or linking
            userSetupAllowed: false
```
