### ISSUE TITLE
Authenticator Config not applied correctly to multiple executions

### ISSUE THREAD

**Issue by RomekCDPR** [adorsys/keycloak-config-cli#1295]
### Current Behavior

The following configuration is not applied to both executions (only to one):

```yaml
authenticatorConfig:
  - alias: email 2FA config
    config:
      codeLength: 6
      codeLifetime: 15
authenticationFlows:
  - alias: CDP Browser - Email OTP
    description: Flow handling Email OTP
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticator: email-two-factor
        authenticatorConfig: email 2FA config
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
  - alias: CDP Registration - Email OTP
    description: Flow handling Email OTP
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticator: email-two-factor
        authenticatorConfig: email 2FA config
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
```

The configuration was correctly applied with 6.2.1-26.0.5 on Keycloak 26.0.8.

### Expected Behavior

Authenticator Config is applied to both executions.

### Steps To Reproduce

```markdown

```

### Environment

- Keycloak Version: 26.1.4
- keycloak-config-cli Version: 6.4.0-26.1.0
