### ISSUE TITLE
Var substitution does not work?

### ISSUE THREAD

**Issue by brunocascio** [adorsys/keycloak-config-cli#249]
**Describe the bug**
Injecting variables into json files seems not to work. I also set `import_var-substitution=true` in my docker-compose.yml but the value is set as literal.
![image](https://user-images.githubusercontent.com/2397875/98268664-92376e00-1f6b-11eb-9cba-f474738670e2.png)

**To Reproduce**

1. Clone this repository
2. Remove benchmark.yml (it contains errors) and reduce moped.json to this content:

```json
{
  "id": "moped",
  "realm": "moped",
  "displayName": "MOPED Realm",
  "displayNameHtml": "${env:MY_ENV_VARIABLE}"
}
```

3. Configure the docker-compose file as following (I fixed it as well)

```yaml
version: '3'
services:
  keycloak:
    image: jboss/keycloak:11.0.2
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
    volumes:
      - ./providers/:/opt/jboss/keycloak/providers/
    networks:
      - keycloak
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - "-c"
      - "standalone.xml"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
  
  keycloak-config-cli:
    image: adorsys/keycloak-config-cli:v2.5.0-11.0.2
    depends_on:
      - keycloak
    networks:
      - keycloak
    volumes:
      - ./contrib/example-config:/config
    environment:
      - keycloak_url=http://keycloak:8080
      - keycloak_user=admin
      - keycloak_password=admin123
      - import_var-substitution=true
      - MY_ENV_VARIABLE=test

networks:
  keycloak:
```

**Expected behavior**

`displayNameHtml` should be `test` instead of `${env:MY_ENV_VARIABLE}`

**Environment (please complete the following information):**
 - Keycloak Version: 11.0.2
 - keycloak-config-cli Version: v2.5.0-11.0.2 (as well latest)
 - Java Version: Running in docker (i.e. 11)
