### ISSUE TITLE
Importing just user has unexpected effects - first time error, second time 409 conflict

### ISSUE THREAD

**Issue by cristichiru** [adorsys/keycloak-config-cli#264]
**Describe the bug**
Importing just user has unexpected effects:
- first run error: `Cannot find user 'bubulete' in realm 'myrealm'`, however the user is created. Later edit: the user was already there, but with different username.
- second run, same input: `HTTP 409 Conflict`.
- Second user is never created, at any step, because there are always errors at the first.

**To Reproduce**
1. Use the following as input file:

    ```yaml
    realm: myrealm
    users:
    -   email: a@a.a
        username: bubulete
        firstName: Bubu
        lastName: Lete
        enabled: true
    -   email: b@b.b
        username: bubulete2
        firstName: Bubu2
        lastName: Lete2
        enabled: true
    ```
2. Run the docker container:

```properties
docker run \
    --rm \
    -e KEYCLOAK_URL="https://keycloak-url"\
    -e KEYCLOAK_USER="admin"\
    -e KEYCLOAK_PASSWORD="supersecret"\
    -e KEYCLOAK_AVAILABILITYCHECK_ENABLED="true"\
    -e KEYCLOAK_AVAILABILITYCHECK_TIMEOUT="30s"\
    -e IMPORT_PATH="/config"\
    -e IMPORT_FORCE="true"\
    -v "/some-dir":"/config" \
    adorsys/keycloak-config-cli:"v2.6.2-10.0.2"
```

**Expected behavior**
1. All users should be created on the first run
2. Second run should update the users, regardless if something changed or not
3. Maybe: if one object (e.g. user) fails, the rest should be imported, the process should continue instead of failing fast.

**Environment (please complete the following information):**
 - Keycloak Version: 10.0.2
 - keycloak-config-cli Version: v2.6.2
 - Java Version: the one in `keycloak-config-cli` docker container

**Additional context**
`IMPORT_FORCE=true` does not seem to have any effect
