### ISSUE TITLE
Cannot resolve variable 'env:MYVAR' (enableSubstitutionInVariables=true)

### ISSUE THREAD

**Issue by todeb** [adorsys/keycloak-config-cli#300]
Hi, 
- I had setup env variable in docker container running keylcoak.
- I had setup audience mapper:
`      "name" : "test.${env:MYVAR}.test.local",
      "protocol" : "openid-connect",
      "protocolMapper" : "oidc-audience-mapper",
      "consentRequired" : false,
      "config" : {
        "id.token.claim" : "true",
        "access.token.claim" : "true",
        "included.custom.audience" : "test.${env:MYVAR}.test.local"
      }`
- Running import triggers:
`4341 --- [           main] d.a.k.config.KeycloakConfigRunner        : Cannot resolve variable 'env:MYVAR' (enableSubstitutionInVariables=true).`

Is it something that I misuderstood and doing wrong?

**Comment by jkroepke** [comment]
Did you enable `import.var-substitution=true` as mention inside README.md? 

https://github.com/adorsys/keycloak-config-cli#variable-substitution

**Comment by todeb** [comment]
By config map, as other env.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
  serviceName: keycloak-headless
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: keycloak
              namespaces:
              - keycloak
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: keycloak-env-vars 
```
```
apiVersion: v1
data:
  MYVAR: "test"
  JGROUPS_DISCOVERY_PROPERTIES: ""
  JGROUPS_DISCOVERY_PROTOCOL: kubernetes.KUBE_PING
  JGROUPS_TRANSPORT_STACK: tcp
  CACHE_OWNERS_COUNT: "2"
  CACHE_OWNERS_AUTH_SESSIONS_COUNT: "2"
  KEYCLOAK_LOGLEVEL: INFO
  PROXY_ADDRESS_FORWARDING: "true"
  JAVA_OPTS: -server -Xms512m -Xmx768m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true 
kind: ConfigMap
metadata:
  labels:
    app: keycloak
  name: keycloak-env-vars
  namespace: keycloak
```
```
java -jar ./keycloak-config-cli-10.0.2.jar \
    --keycloak.url=http://127.0.0.1:30703/auth \
    --keycloak.ssl-verify=true \
    --keycloak.user=keycloak_admin \
    --keycloak.password=pass \
    --import.path=realm-a.json \
    --import.var-substitution=true
```
