### ISSUE TITLE
Support for *_FILE env secrets

### ISSUE THREAD

**Issue by brunocascio** [adorsys/keycloak-config-cli#301]
**Is your feature request related to a problem? Please describe.**
Inject credentials in a non-plain-text way via env variables

**Describe the solution you'd like**

Support for *_FILE env variables (e.g. KEYCLOAK_USER_FILE, KEYCLOAK_PASSWORD_FILE)
This is useful for injecting docker secrets as following:

```yaml
KEYCLOAK_PASSWORD_FILE: /var/run/secrets/keycloak-password
```

**Comment by jkroepke** [comment]
Looking at https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/StringSubstitutor.html

This maybe helps you: 

```
${file:UTF-8:/var/run/secrets/keycloak-password}
${url:UTF-8:file:///var/run/secrets/keycloak-password}
```

Not tested, maybe this works too:

```
${file:UTF-8:${env:KEYCLOAK_PASSWORD_FILE}}
${url:UTF-8:file://${env:KEYCLOAK_PASSWORD_FILE}}
```

**Comment by brunocascio** [comment]
Hey @jkroepke,

Many thanks for your reply!

It seems does not work :/

```yml
keycloak-config:
            image: adorsys/keycloak-config-cli:v3.0.0-12.0.2
            user: "1001"
            networks:
              - auth-stack
            depends_on:
              - keycloak
            secrets:
              - keycloak-password
            environment:
              - KEYCLOAK_URL=http://tasks.keycloak:8080/auth
              - KEYCLOAK_USER=admin
              - KEYCLOAK_PASSWORD=$${file:/var/run/secrets/keycloak-password}
            deploy:
              restart_policy:
                condition: on-failure
```

I got 401 all the time (and the password dis OK) Is there a way to configure debug log level and see which credentials are the CLI using?

**Comment by brunocascio** [comment]
Hey @jkroepke,

Many thanks for your reply!

It seems does not work :/

```yml
keycloak-config:
            image: adorsys/keycloak-config-cli:v3.0.0-12.0.2
            user: "1001"
            networks:
              - auth-stack
            depends_on:
              - keycloak
            secrets:
              - keycloak-password
            environment:
              - KEYCLOAK_URL=http://tasks.keycloak:8080/auth
              - KEYCLOAK_USER=admin
              - KEYCLOAK_PASSWORD=$${file:/var/run/secrets/keycloak-password}
            deploy:
              restart_policy:
                condition: on-failure
```

I got 401 all the time (and the password dis OK) Is there a way to configure debug log level and see which credentials are the CLI using?

**Comment by jkroepke** [comment]
You have to write `${file:UTF-8:/var/run/secrets/keycloak-password}` inside you realm config json.

**Comment by brunocascio** [comment]
I need the keycloak password in order to authenticate against keycloak. It's not a realm configuration. Is the `keycloak.password` config

**Comment by jkroepke** [comment]
I got it. I have to figure out what spring provides out of the box.

**Comment by jkroepke** [comment]
Okay, I found this:

https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/spring-boot-features.html#boot-features-external-config-files-configtree

Based on that, this may worked:

```yaml
keycloak-config:
    image: adorsys/keycloak-config-cli:v3.0.0-12.0.2
    user: "1001"
    networks:
      - auth-stack
    depends_on:
      - keycloak
    secrets:
      - keycloak-password
    environment:
      - SPRING_CONFIG_IMPORT=configtree:/var/run/secrets/
      - KEYCLOAK_URL=http://tasks.keycloak:8080/auth
      - KEYCLOAK_USER=admin
      - keycloak.password=${keycloak-password}
    deploy:
      restart_policy:
        condition: on-failure
```

The `configtree:/var/run/secrets/` will pickup alle file in the folder /var/run/secrets/ and use the file name as key, the file conent as value. Using your example, spring will define a key named `keycloak-password` using the content of `/var/run/secrets/keycloak-password` as value.

Later then, I could re-assign the key keycloak-password to keycloak.password.

Somehow, still using `KEYCLOAK_PASSWOR=${keycloak-password} will raise a "Circular placeholder reference" error.

Thats is how I could solve your issues without coding any extra line of code. Does this fit?

**Comment by jkroepke** [comment]
That may work better, i do not know if it works:

```
keycloak-config:
    image: adorsys/keycloak-config-cli:v3.0.0-12.0.2
    user: "1001"
    networks:
      - auth-stack
    depends_on:
      - keycloak
    secrets:
      - keycloak-password
    environment:
      - SPRING_CONFIG_IMPORT=configtree:/var/run/secrets/
      - KEYCLOAK_URL=http://tasks.keycloak:8080/auth
      - KEYCLOAK_USER=admin
    deploy:
      restart_policy:
        condition: on-failure
secrets:
  keycloak-password:
    file: /var/run/secrets/keycloak/password
```

**Comment by brunocascio** [comment]
Hey @jkroepke,

Thank you so much! It works, here is how it looks like now:

```yaml
keycloak-config:
    image: adorsys/keycloak-config-cli:v3.0.0-12.0.2
    secrets:
      - source: keycloak-password
        target: /run/secrets/keycloak.password
    environment:
      - SPRING_CONFIG_IMPORT=configtree:/run/secrets/
      - KEYCLOAK_URL=http://tasks.keycloak:8080/auth
      - KEYCLOAK_USER=admin
    deploy:
      restart_policy:
        condition: on-failure
```

Cheers! :beers:
