### ISSUE TITLE
Multiple authenticationExecutions with settings don't work

### ISSUE THREAD

**Issue by pmorch** [adorsys/keycloak-config-cli#317]
**Describe the bug**

If I have two `authenticationExecutions`, the first one's settings don't get applied.

Also I think the order is wrong (not sure here, though). When looking at a raw export from an existing realm, it looks like they should be ordered by priority in ascending order. But after import, they appear to be in descending priority order.

Background: We have developed our own Authentication Execution, that has configuration. There can be multiple of these, each with their own configuration. While it works fine when manually configuring them, `keycloak-config-cli` seems to not apply settings for the first one if there are two as in the following example. I've used the "Identity Provider Redirector" in this example, because it is built-in. I have no idea if having multiple of such guys makes sense, but it does make sense in our case of our own in-house developed executions that we can't share.

**To Reproduce**

We have two "Identity Provider Redirector" executions, each with their own configurations:

With this yaml:

```yaml
id: two-ids
realm: two-ids
displayName: Two IDs Realm
authenticationFlows:
  - alias: with-two-ids
    description: browser based authentication
    providerId: basic-flow
    topLevel: true
    builtIn: false
    authenticationExecutions:
      - authenticatorConfig: id1
        authenticator: identity-provider-redirector
        requirement: ALTERNATIVE
        priority: 2
        userSetupAllowed: false
        autheticatorFlow: false
      - authenticatorConfig: id2
        authenticator: identity-provider-redirector
        requirement: ALTERNATIVE
        priority: 3
        userSetupAllowed: false
        autheticatorFlow: false
authenticatorConfig:
  - alias: id1
    config:
      defaultProvider: id1
  - alias: id2
    config:
      defaultProvider: id2
```

I expect to see:

![image](https://user-images.githubusercontent.com/159292/107871726-84678200-6ea4-11eb-84f0-0fbf91147981.png)

But instead I see:

![image](https://user-images.githubusercontent.com/159292/107871716-6bf76780-6ea4-11eb-8d92-d2355a0c2b06.png)

Note how the one for id2 is first, where I expect it to be last because of the `priority`  values.

the one that is first in the YAML for id1 doesn't have any configuration in the GUI after being applied. If I view the "Config" of each of them:

![image](https://user-images.githubusercontent.com/159292/107871812-3606b300-6ea5-11eb-890a-baae922d5326.png)

![image](https://user-images.githubusercontent.com/159292/107871819-43bc3880-6ea5-11eb-813d-3c5307bc9be6.png)

The last one (that I expected to be first) doesn't have any configuration.

**Environment (please complete the following information):**
 - Keycloak Version: 11.0.2
 - keycloak-config-cli Version: Whatever is in the docker image adorsys/keycloak-config-cli:latest pulled this morning
 - Java Version: Whatever is in the docker image adorsys/keycloak-config-cli:latest pulled this morning
