### ISSUE TITLE
Cannot resolve variable 'role_uma_authorization' (enableSubstitutionInVariables=true).

### ISSUE THREAD

**Issue by boxcee** [adorsys/keycloak-config-cli#412]
I exported the realm from Keycloak, removed all IDs and now am trying to import again.

`enableSubstitutionInVariables` is set to `true`, because I want to set a client secret from 'outside'.

I don't understand why I get the above error message.
In the exported `realm.json` there is something like this:
```
"roles": {
  "realm": [
    {
      "name": "uma_authorization",
      "description": "${role_uma_authorization}",
      "composite": false,
      "clientRole": false,
      "containerId": "SUVI",
      "attributes": {}
    },
    ...
```

It seems it tries to resolve that as variable substitution, but this format does not exist in the documented [syntax](https://github.com/adorsys/keycloak-config-cli#variable-substitution).

I am new to Keycloak and don't know what to do now. Is this a bug? Or should the `${role_uma_authorization}` be something else?

**Comment by jkroepke** [comment]
Damn, its correct. There is a incompatibility between keycloak defaults and the substitution function from keycloak-config-cli.

**Comment by jkroepke** [comment]
@boxcee 

Could you try to add the option

```
--import.var-substitution-undefined-throws-exceptions=false
```

Does it help?

**Comment by boxcee** [comment]
@jkroepke okay, I tried this:
```
containers:
        - name: kcadm-setup
          image: bitnami/keycloak-config-cli
          envFrom:
            - secretRef:
                name: {{ .Values.keycloak.auth.existingSecret.name }}
          args:
            - --import.var-substitution-undefined-throws-exceptions
            - "false"
          env:
            - name: KEYCLOAK_URL
              value: http://{{ .Release.Name }}/auth
            - name: KEYCLOAK_USER
              value: {{ .Values.keycloak.auth.adminUser }}
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: "120s"
            - name: IMPORT_PATH
              value: /config
            - name: IMPORT_FORCE
              value: "true"
            - name: IMPORT_VARSUBSTITUTION
              value: "true"
          volumeMounts:
            - mountPath: /config/realm.json
              name: realm
              subPath: realm.json
      volumes:
        - name: realm
          secret:
            secretName: "{{ .Release.Name }}-realm-secret"
```

And got this error:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'import.var-substitution-undefined-throws-exceptions' to boolean:

    Property: import.var-substitution-undefined-throws-exceptions
    Value: 
    Origin: "import.var-substitution-undefined-throws-exceptions" from property source "commandLineArgs"
    Reason: failed to convert java.lang.String to boolean

Action:

Update your application's configuration
```

I will try changing the args line to:
```
args:
  - --import.var-substitution-undefined-throws-exceptions=false
```
