### ISSUE TITLE
clientScope import not works before a change nothing save

### ISSUE THREAD

**Issue by wenerme** [adorsys/keycloak-config-cli#464]
**Describe the bug**

After import

![image](https://user-images.githubusercontent.com/1777211/124365420-757a4400-dc7a-11eb-9738-115cd5c381ea.png)

in this status, the `defaultDefaultClientScopes` and `client.defaultClientScopes` not works

edit, change nothing, then save

![image](https://user-images.githubusercontent.com/1777211/124365445-a6f30f80-dc7a-11eb-8124-3f04d0f9bb3a.png)

now this client scope is works now, both `defaultDefaultClientScopes` and `client.defaultClientScopes` works

**To Reproduce**

import client scope

```yaml
clientScopes:
- name: inc-profile
  protocil: openid-connect
  description: Inc Profile
  attributes:
    include.in.token.scope: "true"
    display.on.consent.screen: "true"
    consent.screen.text: 公司个人信息
  protocolMappers:
  - name: preferred_full_name
    protocol: openid-connect
    protocolMapper: oidc-usermodel-attribute-mapper
    config:
      userinfo.token.claim: true
      user.attribute: fullName
      id.token.claim: true
      access.token.claim: true
      claim.name: preferred_full_name
      jsonType.label: String
```

**Expected behavior**

**Environment (please complete the following information):**
 - Keycloak Version: 14.0
 - keycloak-config-cli Version:4.0.1
 - Java Version: docker

**Additional context**
