### ISSUE TITLE
is it possible to update a built-in flow?

### ISSUE THREAD

**Issue by erkkikeranen** [adorsys/keycloak-config-cli#47]
Hi and thanks for your great tool. 

Sorry if this is written somewhere, but couldn't find help by searching so:

I am trying to update the built-in first broker flow automatically, example:
```
{
      "alias": "first broker login",
      "description": "Actions taken after first broker login with identity provider account, which is not yet linked to any Keycloak account",
      "providerId": "basic-flow",
      "topLevel": true,
      "builtIn": true,
      "authenticationExecutions": [
        {
          "authenticatorConfig": "review profile config",
          "authenticator": "idp-review-profile",
          "requirement": "DISABLED",
          "priority": 10,
          "userSetupAllowed": false,
          "autheticatorFlow": false
        },
        {
          "authenticatorConfig": "create unique user config",
          "authenticator": "idp-create-user-if-unique",
          "requirement": "ALTERNATIVE",
          "priority": 20,
          "userSetupAllowed": false,
          "autheticatorFlow": false
        },
        {
          "requirement": "ALTERNATIVE",
          "priority": 30,
          "flowAlias": "Handle Existing Account",
          "userSetupAllowed": false,
          "autheticatorFlow": true
        }
      ]
    }
```

But I get an obvious exception:

Caused by: de.adorsys.keycloak.config.exception.InvalidImportException: Unable to recreate flow 'first broker login' in realm 'realmname': Deletion or creation of built-in flows is not possible

Question: Is it possible to run a script as update on startup?

**Comment by jkroepke** [comment]
Hi!

builtIn flows are immutable in Keycloak.

In our projects we have to clone the workflow first, then we are able to modify or create/update it. ( you don't have to do it inside the ui). You can define the workflows via json, too.

Like here: https://github.com/adorsys/keycloak-config-cli/blob/develop/example-config/moped.json#L5

Or here (yaml format):

```
      registrationFlow: "beta registration"
      resetCredentialsFlow: "reset encrypted credentials"
      authenticationFlows:
        - alias: beta registration
          description: registration flow
          providerId: basic-flow
          topLevel: true
          builtIn: false
          authenticationExecutions:
            - authenticator: registration-page-form
              requirement: REQUIRED
              priority: 0
              flowAlias: beta registration registration form
              userSetupAllowed: false
              autheticatorFlow: true
```
