### ISSUE TITLE
support initial password

### ISSUE THREAD

**Issue by wenerme** [adorsys/keycloak-config-cli#489]
**Is your feature request related to a problem? Please describe.**

current import user and credential like

```yaml
- username: user
  credentials:
  - type: password
    value: pass
    temporary: true
```

but this will override the password if already exists

**Describe the solution you'd like**
support a initialPassword like

```yaml
- username: user
  credentials:
  - type: password
    value: pass
    temporary: true
    ifNotExists: true # import initial password
```

**Describe alternatives you've considered**

none, do not reimport user

**Additional context**
 used terraform provider before, they support the initialPassword field https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docs/resources/user.md
