### ISSUE TITLE
LDAPStorageMapper not updatable

### ISSUE THREAD

**Issue by mpreu** [adorsys/keycloak-config-cli#498]
EDIT: After checking the feature list again, not sure if bug or feature request, as I am not sure whether the description fits into the `Update identity provider mappers` category.

**Describe the bug**
On a Keycloak instance with READ_ONLY LDAP federation and configured LDAPStorageMappers everything works fine on the initial configuration run. Changing mapper config values after that in the configuration will not be reflected in the instance. No errors from the CLI or Keycloak.

**To Reproduce**
Minimal realm config:

```yaml
realm: test
id: test
displayName: Test Realm
enabled: true
verifyEmail: false
registrationAllowed: false
registrationEmailAsUsername: false
loginWithEmailAllowed: false
duplicateEmailsAllowed: false
resetPasswordAllowed: false
editUsernameAllowed: false
components:
  org.keycloak.storage.UserStorageProvider:
    - name: internal-ldap
      id: internal-ldap
      providerId: ldap
      config:
        vendor:
          - ad
        editMode: 
          - READ_ONLY
        usernameLDAPAttribute: 
          - sAMAccountName
        rdnLDAPAttribute: 
          - cn
        uuidLDAPAttribute: 
          - objectGUID
        userObjectClasses: 
          - "person, organizationalPerson, user, top"
        connectionUrl: 
          - "ldap://xxx:3268"
        usersDn: 
          - "dc=xx"
        customUserSearchFilter: 
          - "(sAMAccountName=*)"
        searchScope: 
          - "2" # sub
        authType: 
          - simple
        bindDn: 
          - "CN=x,OU=x,OU=x,OU=Domain Users,DC=x,DC=x"
        # This reads the REALM-SECRET from /opt/jboss/keycloak/secrets
        bindCredential: 
          - "${vault.bindCredentialLDAP}"
        importEnabled:
          - "true"
        batchSizeForSync: 
          - "1000"
        changedSyncPeriod:
          - "86400"
      subComponents:
        org.keycloak.storage.ldap.mappers.LDAPStorageMapper:
          - name: username
            providerId: user-attribute-ldap-mapper
            config:
              ldap.attribute:
                - sAMAccountName
              user.model.attribute:
                - username
              is.mandatory.in.ldap:
                - "true"
              is.binary.attribute:
                - "false"
              always.read.value.from.ldap:
                - "false"
              read.only:
                - "true"
```

After applying, changing the `config."always.read.value.from.ldap"` from the mapper to `true` will not be reflected. Only deletion of the federation and reapplying the whole configuration helps. Same is true for other fields.

```yaml
...
      subComponents:
        org.keycloak.storage.ldap.mappers.LDAPStorageMapper:
          - name: username
            providerId: user-attribute-ldap-mapper
            config:
              ldap.attribute:
                - sAMAccountName
              user.model.attribute:
                - username
              is.mandatory.in.ldap:
                - "true"
              is.binary.attribute:
                - "false"
              always.read.value.from.ldap:
                - "true"
              read.only:
                - "true"
```

**Expected behavior**
LDAPStorageMapper entries can be changed after initial config run.

**Environment (please complete the following information):**
- Keycloak Version: 14.0.0 (Kubernetes Keycloak Community Operator)
- keycloak-config-cli Version: 4.1.0
- Java Version: 11.0.11
