### ISSUE TITLE
Example for add Identity Provider Links to user

### ISSUE THREAD

**Issue by wenerme** [adorsys/keycloak-config-cli#553]
### Problem Statement

Can't find any example on Identity Provider Links

### Proposed Solution

add a Identity Provider Links json

**Comment by jkroepke** [comment]
Like this?

```
realm: test
id: test
components:
  org.keycloak.storage.UserStorageProvider:
    - name: internal-ldap
      id: internal-ldap
      providerId: ldap
      config:
         ...
users:
  - username: user1
    federationLink: internal-ldap
```
