### ISSUE TITLE
Add support for YAML anchors and aliases

### ISSUE THREAD

**Issue by nigtrifork** [adorsys/keycloak-config-cli#632]
### Problem Statement

The Jackson YamlFactory does not support anchors and aliases.

Anchors and aliases allow you to minimize duplication in the realm config. Example:

```yaml
realm: anchors
enabled: 'true'
users:
  - username: user1
    enabled: 'true'
    attributes: &default-attributes
      attr1:
        - val1
      attr2:
        - val2
      attr3:
        - val3

  - username: user2
    enabled: 'true'
    attributes:
      << : *default-attributes
      attr4:
        - val4
```

### Proposed Solution

Discard the jackson YamlFactory, and use snakeyaml directly in KeycloakImportProvider.java. Snakeyaml is already used by Jackson.

I can make a pull request if you would like this feature.
