### ISSUE TITLE
Update users from Custom User Federation don't work

### ISSUE THREAD

**Issue by Romaixn** [adorsys/keycloak-config-cli#988]
### Current Behavior

When I try to update users from a custom User Federation, I encounter a strange bug. With this dataset, for example: 

```yaml
  "users": [
    {
      "username": "jane.doe@example.com",
      "email": "jane.doe@example.com",
      "firstName": "Jane",
      "lastName": "Doe"
    },
    {
      "username": "john.doe@example.com",
      "email": "john.doe@example.com",
      "firstName": "John",
      "lastName": "Doe"
    },
    {
      "username": "jude.doe@example.com",
      "email": "jude.doe@example.com",
      "firstName": "Jude",
      "lastName": "Doe"
    }
  ],
```

Only the first user updates, and it updates with the data of the last user (it correctly has jane.doe@example.com as email but it gets Jude Doe as firstName/lastName)

I have no errors in logs.

(My custom User Federation only manage email and username, everything else is managed by keycloak.)

### Expected Behavior

I expected users to update correctly.

### Environment

- Keycloak Version: [23.0.4]
- keycloak-config-cli Version: [5]
- Java Version: [17]
